project:
  group: laplacian-arch
  name: frontend-ui-domain-model
  type: domain-model
  namespace: laplacian.arch
  version: '1.0.0'
  description:
    en: |
      The frontend-ui-domain-model project.
    ja: |
      The frontend-ui-domain-model project.
    zh: |
      The frontend-ui-domain-model project.
  source_repository:
    url: https://github.com/laplacian-arch/frontend-ui-domain-model.git
    branch: master
  module_repositories:
    local:
      ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  model_files:
  - 'dest/model'
