package laplacian_arch.client_app_arch
import com.github.jknack.handlebars.Context
import laplacian.gradle.task.generate.ExecutionContext
import laplacian.gradle.task.generate.ProjectEntryResolver
import laplacian_arch.client_app_arch.gradle.ClientAppArchModelEntryResolver

import laplacian_arch.client_app_arch.model.PageList

import laplacian_arch.client_app_arch.model.ClientList

import laplacian_arch.client_app_arch.model.WidgetList

import laplacian_arch.client_app_arch.model.FeatureList

import laplacian.util.*
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import java.io.File
import java.nio.file.FileSystems
import java.nio.file.Files
import java.nio.file.Paths
import java.util.stream.Collectors

/**
 * A test utility class which asserts the content of the files generated by with a template.
 */
class ClientAppArchTemplateAssertion {
    lateinit var context: ExecutionContext
    lateinit var pages: PageList
    lateinit var clients: ClientList
    lateinit var widgets: WidgetList
    lateinit var features: FeatureList

    /**
     * Reads the model objects from the given yaml files.
     */
    fun withModel(files: List<File>): ClientAppArchTemplateAssertion {
        context = ExecutionContext().apply {
            val projectModel = File("laplacian-module.yml")
            if (projectModel.exists()) modelFiles.add(projectModel)
            modelFiles.addAll(files)
            modelEntryResolvers.addAll(listOf(
                ProjectEntryResolver(),
                ClientAppArchModelEntryResolver()
            ))
        }
        context.build()
        pages = context.currentModel.get("pages") as PageList
        clients = context.currentModel.get("clients") as ClientList
        widgets = context.currentModel.get("widgets") as WidgetList
        features = context.currentModel.get("features") as FeatureList
        return this
    }

    /**
     * Reads the model objects from the given yaml files.
     */
    fun withModel(path: String, glob: String = "{*,**/*}.yml"): ClientAppArchTemplateAssertion {
        val m = FileSystems.getDefault().getPathMatcher("glob:$path/$glob")
        val files = Files.walk(Paths.get(path))
                   .filter { m.matches(it) }
                   .map{ it.toFile() }
                   .collect(Collectors.toList())
        withModel(files)
        return this
    }

    /**
     * Reads the model objects from the given yaml expression.
     */
    fun withModelText(text: String): ClientAppArchTemplateAssertion {
        val temp = File.createTempFile(ClientAppArchTemplateAssertion::javaClass.name, ".yml")
        temp.deleteOnExit()
        temp.writeText(text)
        withModel(listOf(temp))
        return this
    }

    lateinit var template: File

    /**
     * Sets the test target template file.
     */
    fun withTemplate(templatePath: String): ClientAppArchTemplateAssertion {
        template = File(templatePath)
        return this
    }

    /**
     * Asserts that the given file and the generated one have the same content.
     */
    fun assertSameContent(toBeSourceCodePath: String, handleModel:ClientAppArchTemplateAssertion.() -> Map<String, Any?> = { emptyMap() }) {
        val child = handleModel.invoke(this)
        val ctx = Context.newContext(context.currentModel, child)
        val actual = template.readText().handlebars().apply(ctx)
        val expect = File(toBeSourceCodePath).readText()
        assertEquals(expect.stripDocComments(), actual.stripDocComments())
    }

    /**
     * Asserts that the generated file from the given template includes the certain content.
     */
    fun assertContains(content: String, handleModel:ClientAppArchTemplateAssertion.() -> Map<String, Any?> = { emptyMap() }) {
        val child = handleModel.invoke(this)
        val ctx = Context.newContext(context.currentModel, child)
        val actual = template.readText().handlebars().apply(ctx).stripDocComments()
        val expect = content.stripDocComments()
        val result = actual.replace("""(\n|^)\s*""".toRegex(), "\n").contains(expect.replace("""(\n|^)\s*""".toRegex(), "\n"))
        assertTrue(result, "\n---\n$expect\n---\nThe above content should be included in the following generated code:\n---\n${actual}")
    }
}